### ISSUE TITLE
RefundUnitsCommandCreator should not be final

### ISSUE THREAD

**Issue by Nek-** [Sylius/RefundPlugin#215]
Copy/Pasting is evil.

This class does a lot more than extracting data from the request. I want to be able to reuse it (my case is API input) to have coherent behavior and avoid copy/pasting.

Making it not final and its methods protected solve the problem with ease. The only other solution is to copy/paste the whole class.

**Comment by vvasiloi** [comment]
Also, it would be nice to have an abstraction as return type.
The basic scenario of adding data to request requires copy/pasting:
- the command, to add the properties
- the command creator, to return the custom command
- the RefundUnitsAction, because it has RefundUnitsCommandCreatorInterface in the constructor which now not compatible with the custom command creator

**Comment by Roshyo** [comment]
Can we have an update regarding this point ?

**Comment by GSadee** [comment]
I'm closing this issue as the possibility to customize has been improved in https://github.com/Sylius/RefundPlugin/pull/312 and the docs for that has been written: https://github.com/Sylius/Sylius/pull/12748
